In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("../data/results.csv")
df1.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [3]:
df1.isnull().sum()

date           0
home_team      0
away_team      0
home_score    72
away_score    72
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [4]:
df1.describe()

         home_score    away_score
count  49306.000000  49306.000000
mean       1.757393      1.182209
std        1.774934      1.402759
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

In [5]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 49378 entries, 0 to 49377
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49378 non-null  str
 1   home_team   49378 non-null  str
 2   away_team   49378 non-null  str
 3   home_score  49306 non-null  float64
 4   away_score  49306 non-null  float64
 5   tournament  49378 non-null  str
 6   city        49378 non-null  str
 7   country     49378 non-null  str
 8   neutral     49378 non-null  bool
dtypes: bool(1), float64(2), str(6)
memory usage: 3.1 MB

In [6]:
df1.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [7]:
df1["date"] = pd.to_datetime(df1['date'])

In [8]:
df1 = df1.sort_values("date").reset_index(drop=True)

In [9]:
df1['tournament'].value_counts()

tournament
Friendly                                             18301
FIFA World Cup qualification                          8771
UEFA Euro qualification                               2824
African Cup of Nations qualification                  2327
FIFA World Cup                                        1036
                                                     ...
Benedikt Fontana Cup                                     1
ConIFA Challenger Cup                                    1
CONIFA World Cup qualification                           1
South Asian Super Cup                                    1
Diamond Jubilee International Football Tournament        1
Name: count, Length: 199, dtype: int64

In [10]:
df1['neutral'].value_counts()

neutral
False    36306
True     13072
Name: count, dtype: int64

In [11]:
df2 = pd.read_csv('../data/ranking_soccer_1901-2023.csv')
df2.head()

,year,rank,team,rating,average_rank,average_rating,one_year_change_rank,one_year_change_rating,matches_total,matches_home,matches_away,matches_neutral,matches_wins,matches_losses,matches_draws,goals_for,goals_against
0,1901,1,England,2013,2,1989,0,−6,73,38,35,0,46,16,11,262,102
1,1901,2,Scotland,1973,1,2018,0,−6,74,37,37,0,53,9,12,277,101
2,1901,3,Wales,1476,3,1488,0,35,69,32,36,1,13,46,10,111,227
3,1901,4,Ireland,1338,4,1306,0,−23,58,29,28,1,6,47,5,65,285
4,1902,1,Argentina,2021,1,2021,−,−,1,0,1,0,1,0,0,6,0

In [12]:
df2.isnull().sum()

year                      0
rank                      0
team                      0
rating                    0
average_rank              0
average_rating            0
one_year_change_rank      0
one_year_change_rating    0
matches_total             0
matches_home              0
matches_away              0
matches_neutral           0
matches_wins              0
matches_losses            0
matches_draws             0
goals_for                 0
goals_against             0
dtype: int64

In [14]:
df2 = df2[['year', 'team', 'rating']]
df2

       year                      team  rating
0      1901                   England    2013
1      1901                  Scotland    1973
2      1901                     Wales    1476
3      1901                   Ireland    1338
4      1902                 Argentina    2021
...     ...                       ...     ...
17195  2023                     Tonga     525
17196  2023                      Niue     496
17197  2023  Northern Mariana Islands     434
17198  2023                     Palau     403
17199  2023             Eastern Samoa     377

[17200 rows x 3 columns]

In [15]:
df2.to_csv('../data/elo_ratings.csv', index=False)